name: 'Deploy to AWS S3'
description: 'Deploy a website to AWS S3'
inputs:
  bucket:
   description: 'The s3 bucket name'
   required: true
  bucket-region:
   description: 'The s3 bucket region'
   required: true
  dist-folder:
   description: 'The folder to deploy'
   required: true
runs:
  using: 'node16'
  main: 'main.js'